name: 'learning_dart'
version: 0.0.1
description: Learning Dart App.
#author: vteial <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  logging: '^0.11.3+1'
  angular: ^4.0.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2
  firebase: '^4.0.0'
  sweetalert_angular_dart:
   
dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.21

transformers:
- angular:
    entry_points:
    - web/main.dart
    - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter